name: WeatherAPI Deployment

on:
  push:
    branches: ["main"]

  # This workflow dispatch, allows us to execute this workflow manually
  workflow_dispatch:

env:
  IMAGE_NAME: weatherapi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%Y.%-m.%-d.%-H.%-M.%-S')" # this is the build number of our image as date

      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Build the Docker image
        working-directory: .
        run: |
          docker build . -t ${{env.IMAGE_NAME}}
          docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:${{steps.build-number.outputs.BUILD_NUMBER}}
          docker tag ${{env.IMAGE_NAME}} ${{env.IMAGE_NAME}}:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push the image to Docker Hub
        run: |
          docker push ${{env.IMAGE_NAME}}:${{steps.build-number.outputs.BUILD_NUMBER}}
          docker push ${{env.IMAGE_NAME}}:latest

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.DEPLOYMENT_TRIGGER_URL}}
          method: "GET"
